### PR TITLE
Upgrading to Rescript 11

### PR DESCRIPTION
**Pull request by ashton**
### Version upgrade
* Upgrading to rescript 11
* react-rescript 0.12.1
* jotai 2.7.1
* rescript-webapi 0.9.1

### Build config
updating to new build config file `rescript.json` instead of `bsconfig.json`

### CODE REVIEW

**Comment by ashton** [comment]
@Fattafatta feel free to ask for any change or suggest anything

**Comment by ashton** [comment]
Just some comments, due to `@greenlabs/rescript-testing-library` not been updated yet, and requires `rescript-react^0.10.3` it's necessary to run a `npm install --force` to install the latest dependencies, but I ran all the tests and everything passed.

**Comment by Fattafatta** [comment]
@ashton thanks a lot for the work!

Since the switch to Rescript 11 is a breaking change, we should bump the version 0.4.0.
Also can you please add a note in the README.md at the top for it. Something like:

Version 0.4.0 and upwards requires Rescript 11.

**Comment by ashton** [comment]
Sure! I'll update the PR

**Comment by ashton** [comment]
@Fattafatta done! Sorry for the delay

**Comment by Fattafatta** [comment]
@ashton no problem. Thanks again, I just published the new version to npm.

**Pull request merged**
